---
# Jira version.
jira_version: "8.9.0"

# Jira download details.
jira_download: "{{ _jira_download[jira_version] }}"

# MySQL JDBC version.
mysql_jdbc_version: "5.1.49"

# MySQL JDBC download details.
mysql_jdbc_download: "{{ _mysql_jdbc_download[mysql_jdbc_version] }}"

# PostgreSQL JDBC version.
postgresql_jdbc_version: "42.2.12"

# PostgreSQL JDBC download details.
postgresql_jdbc_download: "{{ _postgresql_jdbc_download[postgresql_jdbc_version] }}"

# Owner and group for Jira.
jira_owner: "jira"
jira_group: "jira"

# Jira home directory.
jira_home: "/var/atlassian/application-data/jira"

# Jira installation directory.
jira_catalina: "/opt/atlassian/jira"

# JVM minimal and maximum memory usage.
jira_jvm_minimum_memory: "1024m"
jira_jvm_maximum_memory: "1024m"

# Proxy and context path setup.
jira_catalina_connector_proxyname: ~
jira_catalina_connector_proxyport: ~
jira_catalina_connector_scheme: "http"
jira_catalina_connector_secure: "false"
jira_catalina_context_path: "/"

# Atlassian Support recommended JVM arguments.
jira_jvm_support_recommended_args: >-
  -Datlassian.plugins.enable.wait=300
# Session timeout.
jira_session_timeout: "300"