---
# handlers file for jira
- name: jira | systemctl daemon-reload
  systemd:
    daemon_reload: true
  changed_when: false
  ignore_errors: true

- name: jira | systemctl restart jira
  service:
    name: "jira"
    state: "restarted"
    enabled: true
  loop: "{{ ansible_play_hosts }}"
  delegate_to: "{{ item }}"
  run_once: true
  changed_when: false
  ignore_errors: true